[workspace]
members = [
    "blockchain_node",
    "blockchain_node/fuzz"
]

[workspace.dependencies]
tokio = { version = "1.0", features = ["full"] }
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
log = "0.4"
env_logger = "0.10"
futures = "0.3"
libp2p = { version = "0.52", features = ["tokio", "tcp", "dns", "websocket", "noise", "yamux", "ping", "kad", "floodsub"] }
hex = "0.4"
sha2 = "0.10"
blake2 = "0.10"
sha3 = "0.10"
blake3 = "1.4"
chrono = { version = "0.4", features = ["serde"] }
zstd = "0.12"
prometheus = "0.13"
axum = "0.6"
tower-http = { version = "0.4", features = ["cors"] }
thiserror = "1.0"
rayon = "1.7"
sysinfo = "0.29.10"
petgraph = "0.6"
uuid = { version = "1.6.1", features = ["v4", "serde"] }
bumpalo = "3.14.0"
dashmap = "5.5.3"
parking_lot = "0.12.1"
net2 = "0.2.39"
bincode = "1.3.3"

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Your Name <your.email@example.com>"]
description = "A high-performance blockchain implementation"

[workspace.metadata]
default-members = ["blockchain_node"]

[package]
name = "arthachain_node"
version = "0.1.0"
edition = "2021"
description = "ArthaChain node implementation - Hybrid Consensus Blockchain with Social Verification"
authors = ["ArthaChain Team <info@arthchain.com>"]
homepage = "https://arthchain.com"
repository = "https://github.com/DiigooSai/ArthaChain"
license = "MIT"

# Simplified dependencies for standalone benchmarks
[dependencies]
tokio = "1.0"
rand = "0.8"
rayon = "1.7"
criterion = "0.4.0"
blake3 = "1.4.0"
num_cpus = "1.16.0"

[[bin]]
name = "simple_throughput_test"
path = "benches/simple_throughput_test.rs"

[dev-dependencies]
tempfile = "3.8.0"
mockall = "0.11.4"
tokio-test = "0.4"
criterion = "0.4.0"
rand = "0.8.5"
tokio = { version = "1.0", features = ["full"] }
rayon = "1.7.0"

[[bench]]
name = "data_chunking_benchmark"
harness = false
path = "benches/data_chunking_benchmark.rs"

[[bench]]
name = "performance"
harness = false
path = "benches/performance.rs"

[[test]]
name = "high_throughput_tests"
path = "blockchain_node/src/tests/high_throughput_tests.rs"

[[test]]
name = "memmap_storage_tests"
path = "blockchain_node/src/tests/memmap_storage_tests.rs"

[[test]]
name = "network_throughput_tests"
path = "blockchain_node/src/tests/network_throughput_tests.rs"

[[test]]
name = "cross_shard_tests"
path = "blockchain_node/src/tests/cross_shard_tests.rs"

[[test]]
name = "simd_execution_tests"
path = "blockchain_node/src/tests/simd_execution_tests.rs"

[[test]]
name = "zkp_benchmark_tests"
path = "blockchain_node/src/tests/zkp_benchmark_tests.rs"

[[test]]
name = "integration_tests"
path = "blockchain_node/src/tests/integration_tests.rs"

[[bin]]
name = "ultra_high_tps_test"
path = "standalone_benchmarks/ultra_high_tps_test.rs" 