[workspace]
members = [
    "blockchain_node",
    "blockchain_node/fuzz"
]

[workspace.dependencies]
tokio = { version = "1.0", features = ["full"] }
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
log = "0.4"
env_logger = "0.10"
futures = "0.3"
libp2p = { version = "0.52", features = ["tokio", "tcp", "dns", "websocket", "noise", "yamux", "ping", "kad", "floodsub"] }
hex = "0.4"
sha2 = "0.10"
blake2 = "0.10"
sha3 = "0.10"
blake3 = "1.4"
chrono = { version = "0.4", features = ["serde"] }
zstd = "0.12"
prometheus = "0.13"
axum = "0.6"
tower-http = { version = "0.4", features = ["cors"] }
thiserror = "1.0"
rayon = "1.7"

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Your Name <your.email@example.com>"]
description = "A high-performance blockchain implementation"

[workspace.metadata]
default-members = ["blockchain_node"]

[package]
name = "artha-chain-root"
version = "0.1.0"
edition = "2021"
authors = ["Your Name <your.email@example.com>"]
description = "A high-performance blockchain implementation"

[features]
default = ["crypto"]
crypto = ["bls"]
bls = ["blst", "threshold_crypto"]
evm = ["evm-runtime"]
native = []
wasm = ["wasmparser"]

[dependencies]
# Core dependencies
tokio = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
log = { workspace = true }
env_logger = { workspace = true }
futures = { workspace = true }
libp2p = { workspace = true }
hex = { workspace = true }
sha2 = { workspace = true }
blake2 = { workspace = true }
sha3 = { workspace = true }
blake3 = { workspace = true }
chrono = { workspace = true }
zstd = { workspace = true }
prometheus = { workspace = true }
axum = { workspace = true }
tower-http = { workspace = true }
thiserror = { workspace = true }
rayon = { workspace = true }

# Optional dependencies
threshold_crypto = { version = "0.4", optional = true }
z3 = { version = "0.11", optional = true }
blst = { version = "0.3.10", optional = true }
evm-runtime = { version = "0.14", optional = true }
wasmparser = { version = "0.116.1", optional = true }

# Additional dependencies
dotenv = "0.15.0"
clap = { version = "4.4.18", features = ["derive", "env"] }
async-trait = "0.1.74"
num_cpus = "1.16.0"
parking_lot = "0.12.1"
ed25519-dalek = "1.0.1"
rand = "0.7.3"
base64 = "0.21.5"
argon2 = "0.5.2"
multibase = "0.9.1"
bip39 = "2.0.0"
secp256k1 = { version = "0.24.0", features = ["recovery"] }
tiny-keccak = { version = "2.0.2", features = ["keccak"] }
reqwest = { version = "0.11.18", features = ["json"] }
warp = "0.3.5"
juniper = "0.15.11"
tower = { version = "0.4.13", features = ["util"] }
tokio-tungstenite = "0.20.1"
tokio-stream = { version = "0.1.14", features = ["sync"] }
rocksdb = "0.20.1"
ort = "1.14.7"
ndarray = "0.15.6"
tract-onnx = "0.19.11"
bincode = "1.3.3"
tracing = "0.1.37"
tracing-subscriber = "0.3"
metrics = "0.20"
metrics-exporter-prometheus = "0.11"
sputnikvm = { version = "0.11.0-beta.0", optional = true }
ethereum = { version = "0.14.0", optional = true }
ethereum-types = "0.14.1"
rlp = "0.5.2"
jsonrpc-core = "18.0.0"
jsonrpc-http-server = "18.0.0"
ethers-core = "2.0.10"
ethabi = "18.0.0"
primitive-types = "0.12.1"
wasm-bindgen = "0.2.87"
wat = "1.0.71"
once_cell = "1.18.0"
arrayref = "0.3.7"
byteorder = "1.4.3"
k256 = "0.13"
elliptic-curve = "0.13"
pairing = "0.23"
ripemd = "0.1"
num-bigint = "0.4"
num-traits = "0.2"

# New dependency
blockchain_node = { path = "blockchain_node" }

[dev-dependencies]
tempfile = "3.8.0"
criterion = "0.4.0"
mockall = "0.11.4"
tokio-test = "0.4" 