networks:
  artha-testnet:
    driver: bridge

services:
  validator1:
    image: nginx:alpine
    container_name: validator1
    networks:
      - artha-testnet
    ports:
      - "8545:8545"  # RPC
      - "7001:7000"  # P2P (changed from 7000 to avoid conflict)
      - "3000:80"    # API (mapped to nginx)
    volumes:
      - ./explorer:/usr/share/nginx/html
      - ./explorer/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./testnet-genesis.json:/usr/share/nginx/html/api/genesis.json
    command: sh -c "echo '{\"status\":\"running\",\"latest_block_height\":1,\"pending_tx_count\":0,\"active_validators\":1}' > /usr/share/nginx/html/api/status && nginx -g 'daemon off;'"

  explorer:
    image: nginx:alpine
    container_name: explorer
    networks:
      - artha-testnet
    ports:
      - "8080:80"
    volumes:
      - ./explorer:/usr/share/nginx/html
      - ./explorer/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - validator1 