version: '3.8'

networks:
  artha-testnet:
    driver: bridge

services:
  validator1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: validator1
    networks:
      - artha-testnet
    ports:
      - "8545:8545"  # RPC
      - "7000:7000"  # P2P
      - "3000:3000"  # API
    volumes:
      - ./testnet-genesis.json:/app/testnet-genesis.json
      - ./data/validator1:/app/data
    command: >
      --is-genesis
      --node-id validator1
      --genesis-path /app/testnet-genesis.json
      --data-dir /app/data
      --p2p-listen-addr 0.0.0.0:7000
      --rpc-listen-addr 0.0.0.0:8545
      --api-listen-addr 0.0.0.0:3000
      --enable-api
      --shard-id 0
      --bootstrap-peers ""
      --enable-faucet
    environment:
      - RUST_LOG=info
      - ENABLE_TPS_SCALING=true
      - TPS_MULTIPLIER=2.0

  explorer:
    image: nginx:alpine
    container_name: explorer
    networks:
      - artha-testnet
    ports:
      - "8080:80"
    volumes:
      - ./explorer:/usr/share/nginx/html
    depends_on:
      - validator1 