version: '3.8'

services:
  arthachain-node:
    image: ghcr.io/arthachain/node:latest
    container_name: arthachain-validator
    restart: always
    ports:
      - "8080:8080"     # Dashboard & API
      - "30303:30303"   # P2P Port 1
      - "30304:30304"   # P2P Port 2
    volumes:
      - ./data:/data
      - ./config:/config
    environment:
      - NODE_NAME=community-validator
      - NETWORK=mainnet
      - API_PORT=8080
      - P2P_PORT1=30303
      - P2P_PORT2=30304
      - ENABLE_MINING=true
      - ENABLE_DASHBOARD=true
    networks:
      - arthachain-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Monitoring with Prometheus
  prometheus:
    image: prom/prometheus:latest
    container_name: arthachain-prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    networks:
      - arthachain-network
    profiles:
      - monitoring

  # Optional: Grafana Dashboard
  grafana:
    image: grafana/grafana:latest
    container_name: arthachain-grafana
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    networks:
      - arthachain-network
    profiles:
      - monitoring

networks:
  arthachain-network:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data:
