[node]
node_id = "testnet-node-01"
data_dir = "./testnet_data"
log_level = "info"

[network]
network_id = "arthachain-testnet-1"
chain_id = 1337
name = "ArthaChain Testnet"

[consensus]
algorithm = "SVBFT"
block_time = 3
max_block_size = 2097152
max_tx_pool_size = 10000

[network_p2p]
listen_addr = "0.0.0.0:30303"
max_peers = 100
enable_nat = true

[rpc]
http_enabled = true
http_addr = "0.0.0.0"
http_port = 8545
http_cors_origins = ["*"]

ws_enabled = true
ws_addr = "0.0.0.0"
ws_port = 8546

[api]
enabled = true
addr = "0.0.0.0"
port = 3000

[metrics]
enabled = true
prometheus_addr = "0.0.0.0"
prometheus_port = 9090
