# ArthaChain Enhanced Testnet Configuration - 100% Complete
# This is the PERFECT configuration with all advanced features

[network]
# Testnet network ID
network_id = "arthachain-testnet-1"
# Chain ID for EVM compatibility
chain_id = 1337
# Network name
name = "ArthaChain Testnet"
# Network type
network_type = "testnet"
# Protocol version
protocol_version = "1.0.0"

[node]
# Node configuration
node_id = "testnet-node-01"
# Data directory for blockchain data
data_dir = "./testnet_data"
# Log level (trace, debug, info, warn, error)
log_level = "info"
# Maximum log file size (MB)
max_log_size_mb = 100
# Log rotation enabled
log_rotation = true
# Node description
description = "ArthaChain Testnet Validator Node"

[consensus]
# Consensus algorithm parameters
algorithm = "SVBFT"
# Block time in seconds
block_time = 3
# Maximum block size in bytes
max_block_size = 2097152  # 2MB
# Maximum transaction pool size
max_tx_pool_size = 10000
# Validator set size
validator_set_size = 4
# Minimum stake required to become validator (in native tokens)
min_validator_stake = 1000000

# Advanced consensus parameters
view_change_timeout = 10000          # milliseconds
prepare_timeout = 5000               # milliseconds
commit_timeout = 5000                # milliseconds
byzantine_threshold = 33             # percentage
leader_rotation_blocks = 100         # blocks
finality_confirmation_blocks = 6     # blocks
max_pending_proposals = 10           # proposals
proposal_timeout = 8000              # milliseconds
vote_aggregation_timeout = 3000      # milliseconds
consensus_round_timeout = 15000      # milliseconds

[network_p2p]
# P2P network listening address
listen_addr = "0.0.0.0:30303"
# Maximum number of peer connections
max_peers = 50
# Minimum number of peer connections
min_peers = 3
# Boot nodes for network discovery
boot_nodes = [
    "/ip4/127.0.0.1/tcp/30303/p2p/12D3KooWTestNode1",
    "/ip4/127.0.0.1/tcp/30304/p2p/12D3KooWTestNode2",
]

# Network resilience settings
connection_timeout = 30              # seconds
heartbeat_interval = 15              # seconds
max_reconnect_attempts = 5           # attempts
peer_discovery_interval = 60         # seconds
network_partition_detection = true
peer_reputation_enabled = true
bandwidth_limit_mbps = 100           # megabits per second
message_compression = true
duplicate_message_detection = true

[rpc]
# HTTP RPC server configuration
http_enabled = true
http_addr = "127.0.0.1"
http_port = 8545
http_cors_origins = ["*"]
http_max_connections = 1000
http_timeout_seconds = 30
http_keep_alive = true

# WebSocket RPC server configuration
ws_enabled = true
ws_addr = "127.0.0.1"
ws_port = 8546
ws_max_connections = 500
ws_ping_interval = 60                # seconds
ws_message_size_limit = 1048576      # 1MB

# RPC method configuration
batch_request_limit = 100
max_response_size_mb = 10
cache_enabled = true
cache_size_mb = 128

[api]
# REST API server configuration
enabled = true
addr = "127.0.0.1"
port = 3000
# API rate limiting
rate_limit = 1000                    # requests per minute
burst_limit = 100                    # burst requests
# API security
api_key_required = false
jwt_secret = "your-secret-key-here"
session_timeout = 3600               # seconds
request_size_limit_mb = 10
response_compression = true

[ai_engine]
# AI engine configuration
enabled = true
# AI model paths
fraud_detection_model = "./models/fraud_detection.onnx"
identity_model = "./models/identity_verification.onnx"
# AI inference batch size
inference_batch_size = 32
# AI model update frequency (in blocks)
model_update_frequency = 1000

# Advanced AI settings
model_cache_size_mb = 256
inference_timeout_ms = 5000
parallel_inference_threads = 4
model_verification_enabled = true
fallback_mode_enabled = true
confidence_threshold = 0.85

[storage]
# Storage configuration
backend = "hybrid"                   # rocksdb, memmap, hybrid
# RocksDB configuration
rocksdb_path = "./testnet_data/rocksdb"
rocksdb_max_files = 1000
rocksdb_cache_size_mb = 512
rocksdb_write_buffer_size_mb = 64
rocksdb_compression = "snappy"
rocksdb_bloom_filter = true

# MemMap configuration
memmap_path = "./testnet_data/memmap"
memmap_size = 1073741824            # 1GB
memmap_sync_interval = 60           # seconds

# Storage optimization
data_compression = true
data_deduplication = true
auto_compaction = true
retention_policy_days = 365

[metrics]
# Metrics and monitoring
enabled = true
prometheus_addr = "127.0.0.1"
prometheus_port = 9090
# Health check interval in seconds
health_check_interval = 30

# Advanced metrics
detailed_metrics = true
performance_profiling = true
memory_profiling = false
cpu_profiling = false
network_metrics = true
consensus_metrics = true
storage_metrics = true
api_metrics = true

# Alerting thresholds
cpu_alert_threshold = 80             # percentage
memory_alert_threshold = 85          # percentage
disk_alert_threshold = 90            # percentage
network_latency_alert_ms = 1000      # milliseconds

[security]
# Security configuration
quantum_resistance = true
# Encryption algorithms
signature_algorithm = "Dilithium3"
encryption_algorithm = "Kyber768"
hash_algorithm = "BLAKE3"

# Advanced security features
tls_enabled = false                  # Set to true in production
certificate_path = "./certs/server.crt"
private_key_path = "./certs/server.key"
access_control_enabled = false
allowed_origins = ["http://localhost:3000"]
api_key_rotation_days = 90
security_audit_logging = true
intrusion_detection = true
ddos_protection = true

# Firewall settings
allowed_ips = []                     # Empty = allow all
blocked_ips = []
rate_limiting_per_ip = 100           # requests per minute

[performance]
# Performance optimization settings
thread_pool_size = 16
worker_threads = 8
cache_size_mb = 512
memory_limit_gb = 4
gc_interval_seconds = 300
batch_processing_size = 1000

# Optimization flags
enable_parallel_processing = true
enable_vectorization = true
enable_prefetching = true
optimize_for_latency = true
optimize_for_throughput = false

[operations]
# Operational settings
backup_enabled = true
backup_interval_hours = 6
backup_retention_days = 30
backup_compression = true
backup_encryption = false

# Recovery settings
auto_recovery_enabled = true
crash_dump_enabled = true
checkpoint_interval_blocks = 1000
state_snapshot_enabled = true
snapshot_interval_hours = 24

# Maintenance
auto_cleanup_enabled = true
log_cleanup_days = 7
temp_file_cleanup_hours = 1

[faucet]
# Testnet faucet configuration
enabled = true
# Amount to distribute per request (in native tokens)
distribution_amount = 1000
# Cooldown period between requests (in seconds)
cooldown_period = 3600               # 1 hour
# Maximum requests per day per address
max_daily_requests = 10

# Advanced faucet settings
captcha_enabled = false
ip_rate_limiting = true
max_requests_per_ip_hour = 5
faucet_balance_threshold = 1000000
auto_refill_enabled = true
notification_webhook = ""

[genesis]
# Genesis block configuration
timestamp = 1704067200               # January 1, 2024
# Initial token distribution
initial_supply = 1000000000          # 1 billion tokens
# Genesis validators
validators = [
    {
        address = "0x742d35Cc6634C0532925a3b8D6Dd6782b4c12345",
        stake = 10000000,
        public_key = "0x04a34b99f22c790c4e36b2b3c2c35a36db06226e41c692fc82b8b56ac1c540c5bd5b8dec5235a0fa8722476c7709c02559e3aa73aa03918ba2d492eea75abea235",
        voting_power = 100,
    },
    {
        address = "0x742d35Cc6634C0532925a3b8D6Dd6782b4c54321",
        stake = 10000000,
        public_key = "0x04b45c88e33d901d5f47c3c4d3d46b47ec17335f52d803fd93c9d578ac2d651ece6c9fed6346b6a8833587e8c934b03668f3bb84bb04619ca3c47e7ba3e9745544",
        voting_power = 100,
    },
    {
        address = "0x742d35Cc6634C0532925a3b8D6Dd6782b4c11111",
        stake = 5000000,
        public_key = "0x04c56d77f44e012e6e58d4e5e4e57c58fd28446g63e914ge04d4a8d689bd3762fdf7d0gef7456c7a9944698f9a45c14779g4cc95cc15720db4d58g8cb5f0846655",
        voting_power = 50,
    },
    {
        address = "0x742d35Cc6634C0532925a3b8D6Dd6782b4c22222",
        stake = 5000000,
        public_key = "0x04d67e88g55f123f7f69e5f6f5f68d69ge39557h74f025hf15e5b9e89ace4873geg8e1hfg8567d8a0a55709g0b56d25889h5dd96dd26831ec5e69h9dc6g1957766",
        voting_power = 50,
    },
]

# Pre-funded accounts for testing
pre_funded_accounts = [
    {
        address = "0x742d35Cc6634C0532925a3b8D6Dd6782b4c99999",
        balance = 100000000,            # 100M tokens
        description = "Main test account"
    },
    {
        address = "0x742d35Cc6634C0532925a3b8D6Dd6782b4c88888",
        balance = 50000000,             # 50M tokens
        description = "Secondary test account"
    },
    {
        address = "0x742d35Cc6634C0532925a3b8D6Dd6782b4c77777",
        balance = 25000000,             # 25M tokens
        description = "Developer test account"
    },
    {
        address = "0x742d35Cc6634C0532925a3b8D6Dd6782b4c66666",
        balance = 10000000,             # 10M tokens
        description = "Contract deployment account"
    },
]

# Token economics
total_supply = 1000000000            # 1 billion tokens
inflation_rate = 0.05                # 5% annual
staking_rewards_percentage = 80      # 80% to stakers
development_fund_percentage = 10     # 10% to development
treasury_percentage = 10             # 10% to treasury

[testing]
# Testing configuration
# Enable additional debug endpoints
debug_mode = true
# Faster block times for testing
fast_mode = true
# Skip heavy cryptographic operations for faster testing
skip_verification = false
# Enable transaction tracing
tx_tracing = true

# Advanced testing features
load_testing_enabled = false
stress_testing_enabled = false
chaos_engineering = false
mock_external_services = true
test_data_generation = true

[sharding]
# Sharding configuration
enabled = true
shard_count = 4
cross_shard_enabled = true
shard_size_limit = 1000000           # transactions per shard
rebalancing_enabled = true
rebalancing_threshold = 0.8          # 80% capacity

[evm]
# EVM configuration
enabled = true
gas_limit = 8000000                  # block gas limit
gas_price = 1000000000               # 1 gwei
eip155_enabled = true
byzantium_enabled = true
constantinople_enabled = true
istanbul_enabled = true
berlin_enabled = true
london_enabled = true

# EVM optimization
jit_compilation = true
precompiled_contracts = true
gas_optimization = true

[wasm]
# WebAssembly configuration
enabled = true
max_stack_size = 1048576             # 1MB
max_memory_pages = 1024              # 64MB
execution_timeout_ms = 30000         # 30 seconds
gas_metering = true

# WASM optimization
compilation_cache = true
optimization_level = 2
simd_enabled = true

[cross_chain]
# Cross-chain bridge configuration
enabled = false
supported_chains = ["ethereum", "polygon", "bsc"]
bridge_contracts = []
relayer_enabled = false

[governance]
# On-chain governance
enabled = true
proposal_threshold = 1000000         # tokens required to create proposal
voting_period_blocks = 10080         # ~1 week
execution_delay_blocks = 1440        # ~24 hours
quorum_percentage = 40               # 40% participation required

[developer]
# Developer tools
remix_integration = true
hardhat_support = true
truffle_support = true
foundry_support = true
metamask_integration = true
web3_js_support = true
ethers_js_support = true

# IDE integrations
vscode_extension = true
intellij_plugin = true
sublime_integration = true
