# ArthaChain Testnet Configuration

[network]
# Testnet network ID
network_id = "arthachain-testnet-1"
# Chain ID for EVM compatibility
chain_id = 1337
# Network name
name = "ArthaChain Testnet"

[node]
# Node configuration
node_id = "testnet-node-01"
# Data directory for blockchain data
data_dir = "./testnet_data"
# Log level (trace, debug, info, warn, error)
log_level = "info"

[consensus]
# Consensus algorithm parameters
algorithm = "SVBFT"
# Block time in seconds
block_time = 3
# Maximum block size in bytes
max_block_size = 2097152  # 2MB
# Maximum transaction pool size
max_tx_pool_size = 10000
# Validator set size
validator_set_size = 4
# Minimum stake required to become validator (in native tokens)
min_validator_stake = 1000000

[network_p2p]
# P2P network listening address
listen_addr = "0.0.0.0:30303"
# Maximum number of peer connections
max_peers = 50
# Boot nodes for network discovery
boot_nodes = [
    "/ip4/127.0.0.1/tcp/30303/p2p/12D3KooWTestNode1",
    "/ip4/127.0.0.1/tcp/30304/p2p/12D3KooWTestNode2",
]

[rpc]
# HTTP RPC server configuration
http_enabled = true
http_addr = "127.0.0.1"
http_port = 8545
http_cors_origins = ["*"]

# WebSocket RPC server configuration
ws_enabled = true
ws_addr = "127.0.0.1"
ws_port = 8546

[api]
# REST API server configuration
enabled = true
addr = "127.0.0.1"
port = 3000
# API rate limiting
rate_limit = 1000  # requests per minute

[ai_engine]
# AI engine configuration
enabled = true
# AI model paths
fraud_detection_model = "./models/fraud_detection.onnx"
identity_model = "./models/identity_verification.onnx"
# AI inference batch size
inference_batch_size = 32
# AI model update frequency (in blocks)
model_update_frequency = 1000

[storage]
# Storage configuration
backend = "hybrid"  # rocksdb, memmap, hybrid
# RocksDB configuration
rocksdb_path = "./testnet_data/rocksdb"
rocksdb_max_files = 1000
# MemMap configuration
memmap_path = "./testnet_data/memmap"
memmap_size = 1073741824  # 1GB

[metrics]
# Metrics and monitoring
enabled = true
prometheus_addr = "127.0.0.1"
prometheus_port = 9090
# Health check interval in seconds
health_check_interval = 30

[security]
# Security configuration
quantum_resistance = true
# Encryption algorithms
signature_algorithm = "Dilithium3"
encryption_algorithm = "Kyber768"
hash_algorithm = "BLAKE3"

[faucet]
# Testnet faucet configuration
enabled = true
# Amount to distribute per request (in native tokens)
distribution_amount = 1000
# Cooldown period between requests (in seconds)
cooldown_period = 3600  # 1 hour
# Maximum requests per day per address
max_daily_requests = 10

[genesis]
# Genesis block configuration
timestamp = 1704067200  # January 1, 2024
# Initial token distribution
initial_supply = 1000000000  # 1 billion tokens
# Genesis validators
validators = [
    {
        address = "0x742d35Cc6634C0532925a3b8D6Dd6782b4c12345",
        stake = 10000000,
        public_key = "0x1234567890abcdef...",
    },
    {
        address = "0x742d35Cc6634C0532925a3b8D6Dd6782b4c54321",
        stake = 10000000,
        public_key = "0xfedcba0987654321...",
    },
]

# Pre-funded accounts for testing
pre_funded_accounts = [
    {
        address = "0x742d35Cc6634C0532925a3b8D6Dd6782b4c99999",
        balance = 100000000,  # 100M tokens
    },
    {
        address = "0x742d35Cc6634C0532925a3b8D6Dd6782b4c88888",
        balance = 50000000,   # 50M tokens
    },
]

[testing]
# Testing configuration
# Enable additional debug endpoints
debug_mode = true
# Faster block times for testing
fast_mode = true
# Skip heavy cryptographic operations for faster testing
skip_verification = false
# Enable transaction tracing
tx_tracing = true
