[network]
bind_address = "0.0.0.0:30303"
bootstrap_nodes = ["223.228.101.153:30303"]
enable_discovery = true
max_peers = 50
node_id = "vm_validator_node_001"

[api]
bind_address = "0.0.0.0:8080"
enable_cors = true

[consensus]
sync_mode = true
bootstrap_sync = true
validator_enabled = true

[storage]
data_dir = "/root/arthachain_data"
storage_type = "RocksDB"
