name: blockchain_sdk
description: A Dart SDK for interacting with blockchain smart contracts
version: 0.1.0
homepage: https://github.com/yourusername/blockchain-sdk

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  web3dart: ^2.6.1
  http: ^0.13.5
  dio: ^5.0.0
  bip39: ^1.0.6
  bip32: ^2.0.0
  hex: ^0.2.0
  convert: ^3.1.1
  crypto: ^3.0.3
  typed_data: ^1.3.2
  logging: ^1.1.1
  json_annotation: ^4.8.1

dev_dependencies:
  lints: ^2.0.1
  test: ^1.21.0
  build_runner: ^2.3.3
  json_serializable: ^6.6.1 