global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # Add alerting rules here if needed
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # ArthaChain node metrics
  - job_name: 'arthachain-node'
    static_configs:
      - targets: ['node:9090']
    scrape_interval: 10s
    metrics_path: /metrics

  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Caddy metrics
  - job_name: 'caddy'
    static_configs:
      - targets: ['caddy:2019']
    metrics_path: /metrics

  # Node exporter for system metrics (optional)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s
