---
version: "2.0"
services:
  arthachain:
    image: ghcr.io/arthachain/arthachain:latest
    expose:
      - port: 3000
        as: 3000
        to:
          - global: true
      - port: 8545
        as: 8545
        to:
          - global: true
      - port: 8546
        as: 8546
        proto: tcp
        to:
          - global: true
      - port: 9090
        as: 9090
        to:
          - global: true
      - port: 30303
        as: 30303
        proto: tcp
        to:
          - global: true
    command: /bin/sh
    args:
      - >-
        -lc "[ -x /app/real_time_api_server ] && exec /app/real_time_api_server
        || ([ -x /app/api_server ] && exec /app/api_server) || ([ -x
        /app/testnet_api_server ] && exec /app/testnet_api_server) || exec
        /app/arthachain run --config blockchain_node/testnet_config_global.toml"
    env:
      - RUST_LOG=info
    params:
      storage:
        data:
          mount: /mnt/data
          readOnly: false
profiles:
  compute:
    arthachain:
      resources:
        cpu:
          units: 24
        memory:
          size: 48gb
        storage:
          - size: 1tb
          - name: data
            size: 1tb
            attributes:
              persistent: true
              class: beta3
        gpu:
          units: 1
          attributes:
            vendor:
              nvidia:
                - model: a100
  placement:
    dcloud:
      pricing:
        arthachain:
          denom: ibc/170C677610AC31DF0904FFE09CD3B5C657492170E7E52372E48756B71E56F2F1
          amount: 100000
deployment:
  arthachain:
    dcloud:
      profile: arthachain
      count: 1


